# Generated by Django 3.0.4 on 2020-03-29 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fish_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of place')),
                ('lant', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Lant of place')),
                ('long', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Long of place')),
                ('description', models.TextField(verbose_name='Description of place')),
                ('is_Base', models.BooleanField(default=False)),
                ('car_accessibility', models.BooleanField(default=False)),
                ('bus_accessibility', models.BooleanField(default=False)),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рыболовное место',
                'verbose_name_plural': 'Рыболовные места',
            },
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(verbose_name='Description of order')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет о рыбалке',
                'verbose_name_plural': 'Отчеты о рыбалке',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='img/profile/no_photo.png', upload_to=fish_app.models.get_path_to_save_photos)),
                ('first_name', models.CharField(default='Имя', max_length=50, verbose_name='Name profile')),
                ('last_name', models.CharField(default='не назначено', max_length=50, verbose_name='Lastname profile')),
                ('is_professional', models.BooleanField(default=False)),
                ('home_pond', models.CharField(default='', max_length=70, verbose_name='Home pond')),
                ('lovely_pond', models.CharField(default='', max_length=70, verbose_name='Lovely pond')),
                ('fishing_object', models.CharField(default='', max_length=70, verbose_name='Lovely fishing object')),
                ('tackle', models.CharField(default='', max_length=70, verbose_name='tackle')),
                ('fishing_style', models.CharField(default='', max_length=70, verbose_name='fishing_style')),
                ('filters', models.CharField(default='{"is_selfPlaces": "false", "is_Base": "false", "is_carAccessibility": "false", "is_busAccessibility": "false"}', max_length=300, verbose_name='filters')),
                ('friends', models.CharField(default='', max_length=150, verbose_name='Friends')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='PlaceOrderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fish_app.models.get_path_to_save_photos)),
                ('caption', models.CharField(max_length=150, verbose_name='Caption of photo')),
                ('place_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.PlaceOrder')),
            ],
            options={
                'verbose_name': 'Фото отчетов',
                'verbose_name_plural': 'Фото отчетов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', models.CharField(default='', max_length=200, verbose_name='Receivers')),
                ('msg_content', models.TextField(verbose_name='Msg_content')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishingPlaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fish_app.models.get_path_to_save_photos)),
                ('caption', models.CharField(max_length=150, verbose_name='Caption of photo')),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
            ],
            options={
                'verbose_name': 'Фото рыболовного места',
                'verbose_name_plural': 'Фото Рыболовных мест',
            },
        ),
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(default='fishing description', verbose_name='Description of fishing')),
                ('user_list', models.CharField(default='', max_length=100, verbose_name='Users list')),
                ('max_users', models.IntegerField(default=0)),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рыбалка',
                'verbose_name_plural': 'Рыбалки',
            },
        ),
    ]
