# Generated by Django 3.0.2 on 2020-01-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of place')),
                ('lant', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Lant of place')),
                ('long', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Long of place')),
                ('description', models.TextField(verbose_name='Description of place')),
                ('photos', models.CharField(max_length=300, verbose_name='Photos of place')),
            ],
            options={
                'verbose_name': 'Рыболовное место',
                'verbose_name_plural': 'Рыболовные места',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField(verbose_name='Description of order')),
                ('photos', models.CharField(max_length=300, verbose_name='Photos of order')),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
            ],
            options={
                'verbose_name': 'Отчет о рыбалке',
                'verbose_name_plural': 'Отчеты о рыбалке',
            },
        ),
    ]
