# Generated by Django 3.0.6 on 2020-07-14 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fish_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of place')),
                ('lant', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Lant of place')),
                ('long', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Long of place')),
                ('description', models.TextField(verbose_name='Description of place')),
                ('is_Base', models.BooleanField(default=False)),
                ('car_accessibility', models.BooleanField(default=False)),
                ('bus_accessibility', models.BooleanField(default=False)),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рыболовное место',
                'verbose_name_plural': 'Рыболовные места',
            },
        ),
        migrations.CreateModel(
            name='IFish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fish_name', max_length=60, verbose_name='name')),
                ('photo_src', models.CharField(default='', max_length=256, verbose_name='photo_src')),
                ('lat_name', models.CharField(default='fish_lat_name', max_length=60, verbose_name='lat_name')),
                ('another_name', models.CharField(default='fish_another_name', max_length=256, verbose_name='another_name')),
                ('family', models.CharField(default='fish_family', max_length=60, verbose_name='family')),
                ('genus', models.CharField(default='fish_genus', max_length=60, verbose_name='genus')),
                ('kind', models.CharField(default='fish_kind', max_length=60, verbose_name='kind')),
                ('lifestyle', models.CharField(default='fish_lifestyle', max_length=256, verbose_name='lifestyle')),
                ('food_type', models.CharField(default='fish_food_type', max_length=256, verbose_name='food_type')),
                ('habitat', models.TextField(default='fish_habitat', verbose_name='habitat')),
                ('appearance', models.TextField(default='fish_appearance', verbose_name='appearance')),
                ('behavior_features', models.TextField(default='fish_behavior_features', verbose_name='behavior_features')),
                ('food_features', models.TextField(default='fish_food_features', verbose_name='food_features')),
                ('reproduction', models.TextField(default='fish_reproduction', verbose_name='reproduction')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lant', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Lant of place')),
                ('long', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Long of place')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(verbose_name='Description of order')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет о рыбалке',
                'verbose_name_plural': 'Отчеты о рыбалке',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='img/profile/no_photo.png', upload_to=fish_app.models.get_path_to_save_photos)),
                ('first_name', models.CharField(default='Имя', max_length=50, verbose_name='Name profile')),
                ('last_name', models.CharField(default='не назначено', max_length=50, verbose_name='Lastname profile')),
                ('is_professional', models.BooleanField(default=False)),
                ('home_pond', models.CharField(default='', max_length=70, verbose_name='Home pond')),
                ('lovely_pond', models.CharField(default='', max_length=70, verbose_name='Lovely pond')),
                ('fishing_object', models.CharField(default='', max_length=70, verbose_name='Lovely fishing object')),
                ('tackle', models.CharField(default='', max_length=70, verbose_name='tackle')),
                ('fishing_style', models.CharField(default='', max_length=70, verbose_name='fishing_style')),
                ('filters', models.CharField(default='{"is_selfPlaces": "false", "is_Base": "false", "is_carAccessibility": "false", "is_busAccessibility": "false"}', max_length=300, verbose_name='filters')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('datetime_last_active', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('users', models.ManyToManyField(default=[], to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('datetime_sending', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('RD', 'READ'), ('UR', 'UNREAD')], default='UR', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='fish_app.Room')),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fish_app.models.get_path_to_save_photos)),
                ('caption', models.CharField(max_length=150, verbose_name='Caption of photo')),
                ('place_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.PlaceOrder')),
            ],
            options={
                'verbose_name': 'Фото отчетов',
                'verbose_name_plural': 'Фото отчетов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', models.CharField(default='', max_length=200, verbose_name='Receivers')),
                ('msg_content', models.TextField(verbose_name='Msg_content')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'ACCEPT'), ('CN', 'CANCELED'), ('WT', 'WAITING')], default='WT', max_length=2)),
                ('user_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving', to=settings.AUTH_USER_MODEL)),
                ('user_requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishingPlaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fish_app.models.get_path_to_save_photos)),
                ('caption', models.CharField(max_length=150, verbose_name='Caption of photo')),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
            ],
            options={
                'verbose_name': 'Фото рыболовного места',
                'verbose_name_plural': 'Фото Рыболовных мест',
            },
        ),
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lant', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Lant of place')),
                ('long', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Long of place')),
                ('datetime_publication', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(default='fishing description', verbose_name='Description of fishing')),
                ('max_users', models.IntegerField(default=0)),
                ('fishing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.FishingPlace')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рыбалка',
                'verbose_name_plural': 'Рыбалки',
            },
        ),
    ]
