# Generated by Django 3.0.4 on 2020-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.CharField(default='', max_length=250, verbose_name='Friends'),
        ),
    ]
