# Generated by Django 3.0.6 on 2020-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0002_auto_20200715_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(default='', max_length=10, verbose_name='telegram_id'),
        ),
    ]
