# Generated by Django 3.0.4 on 2020-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0002_auto_20200404_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requests_for_friendship',
            field=models.CharField(default='', max_length=250, verbose_name='requests_for_friendship'),
        ),
    ]
