# Generated by Django 3.0.5 on 2020-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0003_profile_requests_for_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.CharField(default='{ "friends": [ ] }', max_length=250, verbose_name='Friends'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requests_for_friendship',
            field=models.CharField(default='{ "requests_for_friendship": [ ] }', max_length=250, verbose_name='requests_for_friendship'),
        ),
    ]
