# Generated by Django 3.0.4 on 2020-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0008_auto_20200412_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
