# Generated by Django 3.0.4 on 2020-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0010_auto_20200413_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
