# Generated by Django 3.0.4 on 2020-04-13 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0011_auto_20200413_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='datetime_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
