# Generated by Django 3.0.4 on 2020-04-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0012_usermessage_datetime_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='datetime_last_active',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
