# Generated by Django 3.0.4 on 2020-04-15 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fish_app', '0013_chat_datetime_last_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='chat',
            new_name='room',
        ),
    ]
